In [109]:
import pandas
import numpy as np
from sklearn.decomposition import PCA

PATH = '/Users/vlasnikita/Documents/vls/py/ml_py_coursera/'

# Загрузите данные close_prices.csv. 
# В этом файле приведены цены акций 30 компаний на закрытии торгов за каждый день периода.
data = pandas.read_csv(PATH + 'lesson_4/close_prices.csv')
del data['date']
# На загруженных данных обучите преобразование PCA с числом компоненты равным 10. 
# Скольких компонент хватит, чтобы объяснить 90% дисперсии?
pca = PCA(n_components=10)
pca.fit(data)
# sum of first 4 elements gives > 0.9
file1 = open(PATH + 'lesson_4/II_1.txt', 'w')
file1.write('4')

# Примените построенное преобразование к исходным данным и возьмите значения первой компоненты.
X = pca.transform(data)
X_first_components = X[:,0]

# Загрузите информацию об индексе Доу-Джонса из файла djia_index.csv. 
# Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?
djia = pandas.read_csv(PATH + 'lesson_4/djia_index.csv')
del djia['date']
pearson = round(np.corrcoef(X_first_components, np.array(djia)[:,0])[1,0], 2)
file2 = open(PATH + 'lesson_4/II_2.txt', 'w')
file2.write(str(pearson))

# Какая компания имеет наибольший вес в первой компоненте? Укажите ее название с большой буквы.
# max_component_index = np.argmax(pca.explained_variance_ratio_)
max_component_index = 0
max_company_index = np.argmax(np.absolute(pca.components_[max_component_index]))
heaviest_company = list(data)[max_company_index]
file3 = open(PATH + 'lesson_4/II_3.txt', 'w')
file3.write(heaviest_company)

In [110]:
data

AXP          BA        CAT       CSCO         CVX         DD  \
0    76.440002  117.510002  85.029999  24.270000  125.519997  59.409999   
1    76.070000  119.000000  85.110001  24.139999  124.489998  59.319997   
2    75.989998  118.510002  84.500000  24.430000  124.070000  59.319997   
3    76.320000  119.379997  84.199997  23.770000  123.489998  59.509996   
4    75.889999  118.739998  83.800003  23.330000  122.639999  59.009995   
5    75.519997  117.500000  83.400002  23.430000  121.500000  58.560000   
6    75.930000  117.750000  83.760002  23.240000  121.320000  58.689999   
7    74.580002  117.839996  84.070000  23.320000  120.830002  58.989999   
8    74.019997  115.239998  83.970001  23.010000  118.250000  57.759995   
9    74.309998  117.199997  84.199997  23.020000  118.129997  58.649998   
10   72.940002  116.690002  83.529999  22.889999  117.870003  58.109998   
11   72.220001  115.440002  82.849998  22.639999  116.730003  57.069996   
12   72.220001  114.470001  83.519997  22.500000  116.129997  56.939998   
13   74.660004  118.900002  84.730003  23.010000  116.379997  58.289998   
14   75.400002  117.980003  85.610001  23.280001  117.669998  57.929998   
15   76.070000  119.459999  86.239998  23.340000  118.580002  58.360000   
16   75.250000  118.180000  85.750000  23.180000  118.150002  58.140000   
17   76.320000  120.339996  86.269997  23.000000  119.160004  59.060001   
18   80.230003  122.290001  85.849998  22.780001  119.519997  59.639998   
19   80.519997  122.519997  87.339996  22.959999  119.650002  59.619998   
20   80.400002  121.470001  87.699997  22.930000  119.820000  59.459998   
21   80.870003  122.480003  89.169998  22.650000  120.639999  60.169996   
22   80.629997  129.020004  83.760002  22.260000  120.129997  60.219999   
23   80.900002  128.979996  84.529999  22.370001  120.559998  61.380000   
24   82.610001  131.190002  84.769997  22.459999  120.589996  61.900001   
25   82.760002  129.880005  84.279999  22.549999  120.910004  61.560000   
26   83.660004  129.660004  84.070000  22.830000  121.500000  61.479996   
27   83.099998  129.679993  83.489998  22.709999  120.300003  61.020000   
28   81.800003  130.500000  83.360001  22.559999  119.959999  61.200000   
29   82.160004  133.029999  83.589996  22.570000  118.010002  61.089998   
..         ...         ...        ...        ...         ...        ...   
344  83.610001  147.220001  81.949997  26.690001  108.349998  73.739996   
345  84.730003  148.600006  83.570000  27.260000  109.309998  75.999995   
346  85.010002  148.000000  83.209999  27.240000  109.610001  76.099999   
347  84.980003  147.580002  84.669998  27.120001  110.430000  75.720003   
348  85.839996  148.039993  83.900002  27.490000  110.180000  75.979999   
349  86.010002  147.919998  83.410004  26.930000  109.980003  75.249996   
350  80.480003  148.089996  83.529999  29.459999  110.860001  76.289997   
351  78.080002  149.729996  85.129997  29.430000  112.779999  76.179999   
352  79.080002  149.919998  85.379997  29.309999  112.400002  76.430002   
353  79.779999  151.169998  84.800003  29.490000  110.440002  76.309994   
354  78.400002  153.750000  83.300003  29.309999  108.349998  76.080003   
355  79.830002  158.309998  84.440002  29.610001  108.599998  76.669994   
356  80.300003  154.740005  83.489998  29.629999  107.860001  77.460001   
357  80.860001  154.380005  84.500000  29.629999  107.959999  77.900002   
358  82.169998  153.009995  85.150002  29.490000  108.580002  77.900002   
359  83.250000  151.729996  83.800003  29.910000  107.059998  78.029996   
360  81.589996  150.850006  82.900002  29.510000  106.680000  77.850000   
361  82.029999  153.800003  83.000000  30.190001  105.900002  78.489992   
362  81.910004  155.570007  82.839996  29.540001  105.160004  78.069996   
363  80.629997  154.350006  81.730003  29.330000  105.160004  78.119998   
364  81.150002  154.470001  81.510002  29.299999  104.730003  78.319998   
365  80.309998  153.119995  80.05999

In [108]:
heaviest_company

'V'

In [105]:
round(pearson, 2)

0.91

['AXP',
 'BA',
 'CAT',
 'CSCO',
 'CVX',
 'DD',
 'DIS',
 'GE',
 'GS',
 'HD',
 'IBM',
 'INTC',
 'JNJ',
 'JPM',
 'KO',
 'MCD',
 'MMM',
 'MRK',
 'MSFT',
 'NKE',
 'PFE',
 'PG',
 'T',
 'TRV',
 'UNH',
 'UTX',
 'V',
 'VZ',
 'WMT',
 'XOM']

0

In [90]:
pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

In [85]:
pearson

0.9096522193050239

In [87]:
djia

^DJI
0    15401.379883
1    15334.589844
2    15273.259766
3    15328.299805
4    15258.240234
5    15129.669922
6    15191.700195
7    15133.139648
8    14996.480469
9    15072.580078
10   14936.240234
11   14776.530273
12   14802.980469
13   15126.070312
14   15237.110352
15   15301.259766
16   15168.009766
17   15373.830078
18   15371.650391
19   15399.650391
20   15392.200195
21   15467.660156
22   15413.330078
23   15509.209961
24   15570.280273
25   15568.929688
26   15680.349609
27   15618.759766
28   15545.750000
29   15615.549805
..            ...
344  17673.019531
345  17884.880859
346  17824.289062
347  17729.210938
348  17868.759766
349  17862.140625
350  17972.380859
351  18019.349609
352  18047.580078
353  18029.849609
354  17985.769531
355  18140.439453
356  18116.839844
357  18209.189453
358  18224.570312
359  18214.419922
360  18132.699219
361  18288.630859
362  18203.369141
363  18096.900391
364  18135.720703
365  17856.779297
366  17995.720703
367  17662.939453
368  17635.390625
369  17895.220703
370  17749.310547
371  17977.419922
372  17849.080078
373  18076.189453

[374 rows x 1 columns]

In [86]:
X[:10]

array([[-50.90240358,  17.63167724,   7.7360209 ,   2.59600961,
          2.37756945,   4.24405501,  12.8830885 ,   3.55657041,
         -5.82197358,  -1.72604005],
       [-52.84690919,  19.14690749,   7.27254551,   4.61857455,
          0.10218206,   3.93551927,  11.06292968,   3.43259929,
         -5.63318106,  -2.0122316 ],
       [-54.61443917,  19.92735811,   8.10995831,   4.92034697,
         -0.42145368,   4.55533467,  10.11922373,   4.17520282,
         -5.38828678,  -2.75269933],
       [-52.60056628,  19.9415712 ,   6.94811275,   4.80624263,
          0.31977948,   5.06550542,   9.84960544,   3.26657913,
         -5.97457399,  -1.92274584],
       [-52.3701233 ,  22.28906366,   8.41086763,   3.83337235,
         -2.46488201,   4.35989686,   7.98869133,   3.45270934,
         -5.7452042 ,  -1.875131  ],
       [-54.65341197,  24.19093915,  10.13993658,   3.49278583,
         -4.59183249,   4.88650065,   6.94018815,   4.58691872,
         -4.88230281,  -1.78552744],
       [-5

In [78]:
X_first_components

array([-50.90240358, -52.84690919, -54.61443917, -52.60056628,
       -52.3701233 , -54.65341197, -52.81257496, -53.6511457 ,
       -56.69272698, -54.40265506, -58.33164549, -61.71626498,
       -61.31940025, -53.79252445, -50.89263448, -49.63740755,
       -52.3876147 , -47.47854294, -43.56033499, -42.55928046,
       -42.45027087, -42.27124797, -43.25272816, -40.05934481,
       -38.49726315, -39.06492263, -38.39304378, -38.40055833,
       -42.38616981, -39.83057417, -41.29548604, -40.43554958,
       -38.49607932, -42.96158052, -38.71252143, -38.83379331,
       -39.90606174, -37.58824522, -34.92356725, -32.96232694,
       -34.52461722, -36.40345948, -37.22194659, -32.95883861,
       -30.59159319, -29.63686919, -27.34513869, -26.90264007,
       -27.41985754, -28.24277351, -31.79501246, -31.39698179,
       -33.14502283, -30.41497345, -30.73495319, -32.3505575 ,
       -30.84313809, -32.84916115, -30.36248061, -29.89452878,
       -25.10690112, -19.92249325, -19.83315396, -19.22

In [79]:
np.array(djia)[:,0]

array([15401.379883, 15334.589844, 15273.259766, 15328.299805,
       15258.240234, 15129.669922, 15191.700195, 15133.139648,
       14996.480469, 15072.580078, 14936.240234, 14776.530273,
       14802.980469, 15126.070312, 15237.110352, 15301.259766,
       15168.009766, 15373.830078, 15371.650391, 15399.650391,
       15392.200195, 15467.660156, 15413.330078, 15509.209961,
       15570.280273, 15568.929688, 15680.349609, 15618.759766,
       15545.75    , 15615.549805, 15639.120117, 15618.219727,
       15746.879883, 15593.980469, 15761.780273, 15783.099609,
       15750.669922, 15821.629883, 15876.219727, 15961.700195,
       15976.019531, 15967.030273, 15900.820312, 16009.990234,
       16064.769531, 16072.540039, 16072.799805, 16097.330078,
       16086.410156, 16008.769531, 15914.620117, 15889.769531,
       15821.509766, 16020.200195, 16025.530273, 15973.129883,
       15843.530273, 15739.429688, 15755.360352, 15884.570312,
       15875.259766, 16167.969727, 16179.080078, 16221.

In [76]:
np.array(djia)[:,0]

array([15401.379883, 15334.589844, 15273.259766, 15328.299805,
       15258.240234, 15129.669922, 15191.700195, 15133.139648,
       14996.480469, 15072.580078, 14936.240234, 14776.530273,
       14802.980469, 15126.070312, 15237.110352, 15301.259766,
       15168.009766, 15373.830078, 15371.650391, 15399.650391,
       15392.200195, 15467.660156, 15413.330078, 15509.209961,
       15570.280273, 15568.929688, 15680.349609, 15618.759766,
       15545.75    , 15615.549805, 15639.120117, 15618.219727,
       15746.879883, 15593.980469, 15761.780273, 15783.099609,
       15750.669922, 15821.629883, 15876.219727, 15961.700195,
       15976.019531, 15967.030273, 15900.820312, 16009.990234,
       16064.769531, 16072.540039, 16072.799805, 16097.330078,
       16086.410156, 16008.769531, 15914.620117, 15889.769531,
       15821.509766, 16020.200195, 16025.530273, 15973.129883,
       15843.530273, 15739.429688, 15755.360352, 15884.570312,
       15875.259766, 16167.969727, 16179.080078, 16221.

In [74]:
X_first_components

array([[-50.90240358],
       [-52.84690919],
       [-54.61443917],
       [-52.60056628],
       [-52.3701233 ],
       [-54.65341197],
       [-52.81257496],
       [-53.6511457 ],
       [-56.69272698],
       [-54.40265506],
       [-58.33164549],
       [-61.71626498],
       [-61.31940025],
       [-53.79252445],
       [-50.89263448],
       [-49.63740755],
       [-52.3876147 ],
       [-47.47854294],
       [-43.56033499],
       [-42.55928046],
       [-42.45027087],
       [-42.27124797],
       [-43.25272816],
       [-40.05934481],
       [-38.49726315],
       [-39.06492263],
       [-38.39304378],
       [-38.40055833],
       [-42.38616981],
       [-39.83057417],
       [-41.29548604],
       [-40.43554958],
       [-38.49607932],
       [-42.96158052],
       [-38.71252143],
       [-38.83379331],
       [-39.90606174],
       [-37.58824522],
       [-34.92356725],
       [-32.96232694],
       [-34.52461722],
       [-36.40345948],
       [-37.22194659],
       [-32

In [69]:
X_first_components

array([[-50.90240358],
       [-52.84690919],
       [-54.61443917],
       [-52.60056628],
       [-52.3701233 ],
       [-54.65341197],
       [-52.81257496],
       [-53.6511457 ],
       [-56.69272698],
       [-54.40265506],
       [-58.33164549],
       [-61.71626498],
       [-61.31940025],
       [-53.79252445],
       [-50.89263448],
       [-49.63740755],
       [-52.3876147 ],
       [-47.47854294],
       [-43.56033499],
       [-42.55928046],
       [-42.45027087],
       [-42.27124797],
       [-43.25272816],
       [-40.05934481],
       [-38.49726315],
       [-39.06492263],
       [-38.39304378],
       [-38.40055833],
       [-42.38616981],
       [-39.83057417],
       [-41.29548604],
       [-40.43554958],
       [-38.49607932],
       [-42.96158052],
       [-38.71252143],
       [-38.83379331],
       [-39.90606174],
       [-37.58824522],
       [-34.92356725],
       [-32.96232694],
       [-34.52461722],
       [-36.40345948],
       [-37.22194659],
       [-32

In [71]:
np.array(djia)

array([[15401.379883],
       [15334.589844],
       [15273.259766],
       [15328.299805],
       [15258.240234],
       [15129.669922],
       [15191.700195],
       [15133.139648],
       [14996.480469],
       [15072.580078],
       [14936.240234],
       [14776.530273],
       [14802.980469],
       [15126.070312],
       [15237.110352],
       [15301.259766],
       [15168.009766],
       [15373.830078],
       [15371.650391],
       [15399.650391],
       [15392.200195],
       [15467.660156],
       [15413.330078],
       [15509.209961],
       [15570.280273],
       [15568.929688],
       [15680.349609],
       [15618.759766],
       [15545.75    ],
       [15615.549805],
       [15639.120117],
       [15618.219727],
       [15746.879883],
       [15593.980469],
       [15761.780273],
       [15783.099609],
       [15750.669922],
       [15821.629883],
       [15876.219727],
       [15961.700195],
       [15976.019531],
       [15967.030273],
       [15900.820312],
       [160

In [38]:
X

array([[-50.90240358,  17.63167724,   7.7360209 , ...,   3.55657041,
         -5.82197358,  -1.72604005],
       [-52.84690919,  19.14690749,   7.27254551, ...,   3.43259929,
         -5.63318106,  -2.0122316 ],
       [-54.61443917,  19.92735811,   8.10995831, ...,   4.17520282,
         -5.38828678,  -2.75269933],
       ...,
       [ 83.79819948,  16.95241334,  -8.25265611, ...,   2.92390381,
         -4.59543822,  -2.99033503],
       [ 79.19578947,  19.14436008,  -6.93262976, ...,   3.40475421,
         -3.66793327,  -3.57607629],
       [ 82.96885933,  13.13513974,  -9.07644299, ...,   3.75100423,
         -4.79172198,  -3.03918865]])

In [27]:
pca.

AttributeError: 'PCA' object has no attribute 'shape'

In [17]:
pca.explained_variance_ratio_

array([0.73897118, 0.11007169, 0.04995088, 0.0287492 , 0.02215448,
       0.01931577, 0.00674853, 0.00614091, 0.00320594, 0.00305611])

753.5393640412499