In [72]:
import pandas
import numpy as np
from sklearn.metrics import roc_auc_score
import math

PATH = '/Users/vlasnikita/Documents/vls/py/ml_py_coursera/'

data = pandas.read_csv(PATH + 'lesson_3/data-logistic.csv', header=None)
y = data.values[:, :1].T[0]
X = data.values[:, 1:]

def distance (x, y):
    return np.sqrt(np.square(y[0] - x[0]) + np.square(y[1] - x[1]))

def sigmoid (w1, w2, x1, x2):
    return 1 / (1 + np.exp(-w1 * x1 - w2 * x2))

def gradient (w, k, X, y, C, epsilon, max_iterations):
    w_1, w_2 = w
    i = 0
    end_i = 0
    result = []
    
    for i in range(max_iterations):
        end_i = i
        w_1_new = w_1 + k * np.mean(
            y * X[:,0] * (
                1 - 1 / (1 + np.exp(-y * (w_1 * X[:,0] + w_2 * X[:,1])))
            ) - k * C * w_1
        )
        
        w_2_new = w_2 + k * np.mean(
            y * X[:,1] * (
                1 - 1 / (1 + np.exp(-y * (w_1 * X[:,0] + w_2 * X[:,1])))
            ) - k * C * w_2
        )
        
#         print w_1_new, w_2_new

        if distance((w_1, w_2), (w_1_new, w_2_new)) < epsilon:
            break
            
        w_1, w_2 = w_1_new, w_2_new
        
    for j in range(len(y)):
        result.append(sigmoid(w_1, w_2, X[j,0], X[j,1]))

    print 'C: {}, number of iterations: {}'.format(C, end_i)
    return result

w = [0.0, 0.0]
k = 0.1
epsilon = 0.00001
max_iterations = 10000
C = 0
C_l2 = 10

y_score = gradient( w, k, X, y, C, epsilon, max_iterations )
y_score_l2 = gradient( w, k, X, y, C_l2, epsilon, max_iterations )

print round(roc_auc_score(y, y_score), 3)
print round(roc_auc_score(y, y_score_l2), 3)

C: 0, number of iterations: 243
C: 10, number of iterations: 44
0.927
0.937


In [47]:
X[0,0]

-0.6638265368249999

In [48]:
X[1,0]

1.9945955012799998

In [46]:
X[:,0]

array([-6.63826537e-01,  1.99459550e+00, -1.24739492e+00,  2.30937425e+00,
        8.49143314e-01,  1.45427095e+00,  2.25422743e+00, -6.75795166e-02,
       -8.61960913e-01,  6.99178929e-01, -1.61479961e-01, -1.47102261e-01,
        8.02959560e-02,  1.72065543e+00,  1.57395765e+00,  1.16844518e+00,
       -6.66273601e-02,  1.16335473e+00,  2.09696979e+00,  3.03570513e+00,
        8.31852059e-01, -1.29778002e+01, -8.42603085e-01, -4.73536723e-01,
        1.54037313e+00,  4.95341113e-01,  2.09148604e+00,  2.93705461e+00,
       -5.01666814e-01,  8.30206648e-01, -3.90148300e-01, -5.27212710e-01,
        3.37816843e+00,  3.37315300e+00, -2.10285721e-01,  2.54252027e+00,
        1.99496894e+00,  1.94828754e+00,  1.26893596e+00,  2.61003333e+00,
        1.85952947e+00, -1.08183554e+00,  1.07128284e+00, -2.56858396e-01,
        9.38829978e-02,  1.60243555e+00,  4.17917351e+00, -3.87270460e-01,
        7.08176077e-01,  3.94512322e-02,  1.89654827e+00,  2.65671265e-01,
        1.20339278e+00,  

NameError: name 'w' is not defined

In [17]:
print X[:10, ,0]

[[-0.66382654 -0.13852572]
 [ 1.9945955   2.46802468]
 [-1.24739492  0.74942464]
 [ 2.30937425  1.89983556]
 [ 0.84914331  2.40774982]
 [ 1.45427095 -0.66541571]
 [ 2.25422743  2.26378585]
 [-0.06757952  1.4691411 ]
 [-0.86196091 -0.82485558]
 [ 0.69917893  2.03248761]]


In [19]:
print X[:10,0]

[-0.66382654  1.9945955  -1.24739492  2.30937425  0.84914331  1.45427095
  2.25422743 -0.06757952 -0.86196091  0.69917893]


In [20]:
print X[:10,1]

[-0.13852572  2.46802468  0.74942464  1.89983556  2.40774982 -0.66541571
  2.26378585  1.4691411  -0.82485558  2.03248761]


In [30]:
y

array([-1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,
       -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1., -1.,
        1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,
        1.,  1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1.,
       -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1., -1.,
        1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,
       -1.,  1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1., -1.,
       -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1., -1.,
       -1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,
        1., -1., -1., -1.,  1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1.,
       -1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,
       -1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1

In [31]:
-y

array([ 1., -1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,
        1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1., -1., -1.,  1.,
       -1., -1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1., -1., -1., -1.,
        1., -1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,
       -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
       -1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,
        1., -1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1., -1.,  1.,
        1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,  1., -1., -1.,
       -1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,
        1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1.,  1.,
        1., -1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1

In [28]:
y * X[:,0]

array([ 6.63826537e-01,  1.99459550e+00,  1.24739492e+00,  2.30937425e+00,
        8.49143314e-01,  1.45427095e+00,  2.25422743e+00,  6.75795166e-02,
        8.61960913e-01,  6.99178929e-01,  1.61479961e-01,  1.47102261e-01,
       -8.02959560e-02, -1.72065543e+00,  1.57395765e+00, -1.16844518e+00,
        6.66273601e-02,  1.16335473e+00,  2.09696979e+00,  3.03570513e+00,
       -8.31852059e-01, -1.29778002e+01,  8.42603085e-01,  4.73536723e-01,
       -1.54037313e+00, -4.95341113e-01,  2.09148604e+00,  2.93705461e+00,
        5.01666814e-01, -8.30206648e-01,  3.90148300e-01,  5.27212710e-01,
        3.37816843e+00,  3.37315300e+00,  2.10285721e-01, -2.54252027e+00,
        1.99496894e+00,  1.94828754e+00, -1.26893596e+00,  2.61003333e+00,
        1.85952947e+00,  1.08183554e+00,  1.07128284e+00,  2.56858396e-01,
       -9.38829978e-02,  1.60243555e+00,  4.17917351e+00,  3.87270460e-01,
       -7.08176077e-01,  3.94512322e-02,  1.89654827e+00,  2.65671265e-01,
       -1.20339278e+00,  

In [34]:
w

NameError: name 'w' is not defined

In [27]:
len(X[:,0])

205

[[-6.63826537e-01 -1.38525717e-01]
 [ 1.99459550e+00  2.46802468e+00]
 [-1.24739492e+00  7.49424636e-01]
 [ 2.30937425e+00  1.89983556e+00]
 [ 8.49143314e-01  2.40774982e+00]
 [ 1.45427095e+00 -6.65415709e-01]
 [ 2.25422743e+00  2.26378585e+00]
 [-6.75795166e-02  1.46914110e+00]
 [-8.61960913e-01 -8.24855578e-01]
 [ 6.99178929e-01  2.03248761e+00]
 [-1.61479961e-01  4.95461855e-01]
 [-1.47102261e-01  4.19646539e-01]
 [ 8.02959560e-02 -1.15609708e+00]
 [ 1.72065543e+00 -1.08066154e+00]
 [ 1.57395765e+00  1.78543356e+00]
 [ 1.16844518e+00 -6.45619241e-01]
 [-6.66273601e-02 -1.05974659e+00]
 [ 1.16335473e+00  1.74588676e+00]
 [ 2.09696979e+00  1.12963766e+00]
 [ 3.03570513e+00  2.14283780e+00]
 [ 8.31852059e-01 -6.06776832e-01]
 [-1.29778002e+01 -4.57305579e+00]
 [-8.42603085e-01 -1.07628156e+00]
 [-4.73536723e-01 -7.34473331e-01]
 [ 1.54037313e+00  1.67920518e-01]
 [ 4.95341113e-01  6.67507237e-02]
 [ 2.09148604e+00  2.55000484e+00]
 [ 2.93705461e+00  3.26080036e+00]
 [-5.01666814e-01  3